apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
  namespace: mytg
spec:
  replicas: 5
  selector:
    matchLabels:
     app: tomcat
  template:
    metadata:
     labels:
       app: tomcat
    spec:
     imagePullSecrets:
       - name: mypasswd-for-custom-img
     containers:
       - name: tomcat
         image:  cdtsbikaner/devops150624:BUILD_NUMBER
         ports:
          - containerPort: 8080
      
